### ISSUE TITLE
[lns] {STOPMOVIE} is handled as text instead of an event

### ISSUE THREAD

**Issue by pmrowla** [pmrowla/pylivemaker#10]
There is a weird bug in injecting lns when there is just the label.

lns
```
{STOPMOVIE}

{CHANGECG "動画" "グラフィック\動画\みらい2\余韻.gal" "REPEAT" "1" "1000" "0" "0" "" "1"}

{PLAYSND "BGM\【緊張・不安・謎・不気味】緊張感のある感じ.wav" "BGM" "REPEAT" "400" "0"}

{PLAYSND "SE\余韻2.wav" "SE" "REPEAT" "800" "0"}

{PLAYSND "SE\フェラ-くちゅ+ぷちゅ.wav" "SE2" "REPEAT" "800" "0"}

{PLAYSND "VOICE\J06.wav" "VOICE" "REPEAT" "1000" "0"}

<TXSPN>Doctor"Haaa... That was great, Mirai-chan..."
```
But after injecting it is:

```
<TXSPN>{STOPMOVIE}{CHANGECG "動画" "グラフィック\動画\みらい2\余韻.gal" "REPEAT" "1" "1000" "0" "0" "" "1"}
```
EDIT:
Tryed to workaround it, but this breaks playing movie files as it removes {STOPMOVIE} when it is inside .lns

_Originally posted by @LioMajor in https://github.com/pmrowla/pylivemaker/issues/9#issuecomment-517749576_

**Comment by pmrowla** [comment]
ok, as noted in #11, the actual bug here is that {STOPMOVIE} isn't being recognized as an event, and is just reinserted as a text string. @LioMajor can you send me a link to the actual lsb file containing this script?

**Comment by LioMajor** [comment]
I added it to the post renamed as txt file

**Comment by LioMajor** [comment]
@pmrowla did you manage to sort out the bug for fixing it?

**Comment by pmrowla** [comment]
I've identified the problem, but don't have a fix for it yet.
The bug is caused by a tag parsing regex that is too greedy.

The LNS compiler currently interprets the sequence
```
{STOPMOVIE}
{CHANGECG "動画" "グラフィック\動画\みらい2\余韻.gal" "REPEAT" "1" "1000" "0" "0" "" "1"}
```
as if it was one complete event with the tag:
`{STOPMOVIE}{CHANGECG "動画" "グラフィック\動画\みらい2\余韻.gal" "REPEAT" "1" "1000" "0" "0" "" "1"}`
instead of as two separate event tags.

This in turn causes the tag parser to fail, which causes the two combined events to be handled as plaintext.
