### ISSUE TITLE
Translated 0 Lines

### ISSUE THREAD

**Issue by num421337** [pmrowla/pylivemaker#105]
* pylivemaker version:Latest
* Python version:Latest
* Operating System: Windows 11
* LiveMaker game: [RJ156674][4H] 恥辱アイドル咲希はるか Ver.1.20

### Description

Many LSB's with text extracted them all, ran them through translator ++ and when I try to insert them I get   

  Translated 0 lines
  Failed to translate 0 lines
  Ignored 0 untranslated lines

### What I Did

```
lmlsb extractcsv --encoding=utf-8-sig 00000251.lsb 00000251.csv
lmlsb insertcsv --encoding=utf-8-sig 00000251.lsb 00000251.csv
```
[00000251.csv](https://github.com/pmrowla/pylivemaker/files/11793417/00000251.csv)
[00000251.lsb.txt](https://github.com/pmrowla/pylivemaker/files/11793418/00000251.lsb.txt)

**Comment by kiraio-moe** [comment]
Seems like Translator++ adding the full path to the LSB file in extracted CSV, so it will fail to patch the original LSB.

CSV (Edited using Translator++)
![csv_translator++](https://github.com/pmrowla/pylivemaker/assets/58289710/5b5dc504-cd21-4ad6-a064-203f2a39da55)

CSV (Directly exctracted using pylivemaker)
![csv_extracted](https://github.com/pmrowla/pylivemaker/assets/58289710/d4f4bdbf-c826-49ed-ad00-20b628b59ef6)

To fix this, you need to remove `game_files\New folder\game_files\New folder\` from the CSV file edited using Translator++.
![csv_translator++_fix](https://github.com/pmrowla/pylivemaker/assets/58289710/b6a57b01-e003-4236-9487-536509784668)

Result
![csv_translator++_fix_output](https://github.com/pmrowla/pylivemaker/assets/58289710/7d345d06-1297-489f-b247-7eb2b7dec6c0)

**Comment by kiraio-moe** [comment]
Hope that help :)

**Comment by num421337** [comment]
That's really weird that it would mess them up like that.
