### ISSUE TITLE
CSV Insert not working with spanish characters

### ISSUE THREAD

**Issue by Alexeir-TL** [pmrowla/pylivemaker#108]
* pylivemaker version: 1.0.4
* Python version: 3.10.6
* Operating System: Windows
* LiveMaker game: 03.14.08.16

Description
Not sure if this possible, just wanted to make sure, was trying to insert text into a script, text contained spanish characters "ñ" and íóúáé. 

It wasnt able to  patch the line, Is there a way to correct this and properly insert it?

### What I Did

```
lmlsb insertcsv --encoding=utf-8-sig 00000001.lsb 00000001.csv
Patching 00000001.lsb ...
2023-08-25 23:23:51.896 | WARNING  | livemaker.lsb.lmscript:replace_text_blocks:598 - Failed to translate text block <pylm:text:00000001.lsb:82:0> 'ñ' is not a valid CP932 character.
  Translated 1 lines
  Failed to translate 1 lines
  Ignored 4864 untranslated lines
Backing up original LSB.
Wrote new LSB.
```

**Comment by pmrowla** [comment]
The livemaker engine only supports CP932 (windows shift-jis), so by default you can't use any characters that are not in shift-jis (which means no latin characters with accent marks).

It is possible to patch the engine to use an alternate windows locale/codepage, but this requires some extra work to both patch the engine and requires modifying pylivemaker to use the same codepage. This is not something that is officially supported in pylivemaker, but you can see this thread for info: https://github.com/pmrowla/pylivemaker/issues/14
