### ISSUE TITLE
[lmpatch] support split archives

### ISSUE THREAD

**Issue by pmrowla** [pmrowla/pylivemaker#12]
livemaker.archive supports writing split archives now, but the CLI patching tool needs to be updated as well.

**Comment by pmrowla** [comment]
`lmpatch` should work for generating split output now

If input archive has `.ext` file extension, output will be automatically split.
If input archive is `.dat` you need to pass the `--split` option to get split output.

@LioMajor I'd appreciate it if you can test this w/your game and verify that this works properly

**Comment by LioMajor** [comment]
Maybe instead having --split, autosplit if it exceeds 1.073.741.824 bytes if the game has no .ext would be okay too (that's what i did manually with hex editor to make it work).

```
C:\tt\rina\tt\output>del *.bak
C:\tt\rina\tt\output>lmpatch game.ext 00000001.lsb
Generating new archive contents...
  [####################################]  100%                                                                     
Writing new archive files...
Cleaning up temporary files...
C:\tt\rina\tt\output>del *.bak
C:\tt\rina\tt\output>lmpatch game.ext 000006D2.lsb
Generating new archive contents...
  [####################################]  100%                                                                     
Writing new archive files...
Cleaning up temporary files...
C:\tt\rina\tt\output>del *.bak
C:\tt\rina\tt\output>lmpatch game.ext 000006E7.lsb
Generating new archive contents...
  [####################################]  100%
```
I have batched it up to do patching the files inside, so far it works and the game runs like it is supposed to be.

A --nobak option would be nice when you have time for it :)

**Comment by pmrowla** [comment]
My only concern with doing it that way is that I am not sure if livemaker always splits game archives at 1GB? There's no internal engine limitation that requires that limit as far as I can tell from their unpacking code, so I thought it was safer this way for `.dat` files. It's automatic for `.ext` since having the separate index file already implies that the data will be split.

Also, it wasn't documented but lmpatch already has `--no-backup`
