### ISSUE TITLE
Where is PR_FONTCHANGEABLED for BackLog Text?

### ISSUE THREAD

**Issue by xenei** [pmrowla/pylivemaker#120]
Normally this wouldn't phase me, but for this game I'm playing right now, I can't get the backlog text to switch from full-width to half-width at all. Usually, just changing the PR_FONTCHANGEABLED value to 0 does the trick, but the backlog is still full-width this time around.

Do you have any ideas on where the setting for the backlog's PR_FONTCHANGEABLED might be hiding or at what .lsb should I be looking in?

**Comment by xenei** [comment]
Nevermind, it was easy to figure it out.

**Comment by blackfan321** [comment]
@xenei Hi, could you please tell me about your solution?
