### ISSUE TITLE
Asking for help: How to modify the title

### ISSUE THREAD

**Issue by wfan-os** [pmrowla/pylivemaker#130]
* pylivemaker version: 3.0
* Python version: 3.10.10
* Operating System: Windows 11
* LiveMaker game: TS魔法少女セイントチェリ

### Description

I actually successfully translated the game. However, I also want to edit the title on the window of the game program, which for example is like this:

![Screenshot 2024-02-22 135254](https://github.com/pmrowla/pylivemaker/assets/72018068/2d900748-7d12-4c7b-a8e6-813ff7bb96e0)

I found it really hard to locate the title in the exe file. I cannot find the matched string.

**Comment by pmrowla** [comment]
It's been a while since I looked into it, but iirc the window title isn't hard coded in the exe. It gets loaded from the livemaker project configuration. I think you should be able to just edit the `Project Name` field in `live.lpb` (don't edit anything else in the lpb)

```
$ lmlpb edit live.lpb
```
