### ISSUE TITLE
About lmlsb Insert

### ISSUE THREAD

**Issue by jetstream1239** [pmrowla/pylivemaker#15]
Hi I use lmlsb Insert to update my .lsb
The log is:
D:\Google download\pylivemaker-master (1)\pylivemaker-master\livemaker\translated_scripts>lmlsb insert --no-backup 00000011.lsb D:\00000011-00000055.lns 17
Scenario 00000055 at line 17 will be replaced.
Wrote new LSB.

but when i see the new LSB file, it didn't change. so i am confused, can you tell me how can i do pls?
(pls forgive my poor english)

**Comment by pmrowla** [comment]
It looks like you are using the command correctly. Are you sure the LSB file is not being updated?

If you do `lmlsb dump 00000011.lsb` it still shows the original (non-translated) script for line 17?

**Comment by jetstream1239** [comment]
I think it is not being updated, I  lmlsb dump  the new LSB,but it still shows the original scripts

**Comment by jetstream1239** [comment]
I can Screenshot some pic to show you

**Comment by pmrowla** [comment]
It would also help if you can upload your `00000011.lsb` and (translated/modified) `00000011-00000055.lns` files to dropbox or something like that

**Comment by jetstream1239** [comment]
![image](https://user-images.githubusercontent.com/40359897/72219686-ab84af00-3540-11ea-9dc1-ea847f4804b7.png)
![image](https://user-images.githubusercontent.com/40359897/72219701-d1aa4f00-3540-11ea-9ab7-d689abb20201.png)
![image](https://user-images.githubusercontent.com/40359897/72219719-ebe42d00-3540-11ea-897f-be392f17fe90.png)

![image](https://user-images.githubusercontent.com/40359897/72219726-fe5e6680-3540-11ea-98ee-0748f59b4f7f.png)

**Comment by jetstream1239** [comment]
[translated_scripts.zip](https://github.com/pmrowla/pylivemaker/files/4050690/translated_scripts.zip)
 Here is the lsb and lns file

**Comment by pmrowla** [comment]
It works for me on my machine using the files you uploaded. I can't test it on a windows box right now, but I'll try to get to it tomorrow.

```
translated_scripts  py:pylivemaker ❯ lmlsb dump -m xml 00000011.lsb > orig.xml
Label lookup not yet implemented.
...

translated_scripts  py:pylivemaker ❯ ls
00000011-00000055.lns  00000011.lsb  00000011.lsb.bak  orig.xml

translated_scripts  py:pylivemaker ❯ lmlsb insert --no-backup 00000011.lsb 00000011-00000055.lns 17
Scenario 00000055 at line 17 will be replaced.
Wrote new LSB.

translated_scripts  py:pylivemaker ❯ lmlsb dump -m xml 00000011.lsb > new.xml
Label lookup not yet implemented.
...

translated_scripts  py:pylivemaker ❯ diff orig.xml new.xml
1189c1189
< ;    1: TDecorate(count=2675, unk2=4294967295, unk3=4294967295, unk4=0, unk5=0, unk6=0, unk7=4294967295, unk8=, unk9=, unk10=4294967295, unk11=4294967295)
---
> ;    1: TDecorate(count=2644, unk2=4294967295, unk3=4294967295, unk4=0, unk5=0, unk6=0, unk7=4294967295, unk8=, unk9=, unk10=4294967295, unk11=4294967295)
1195c1195
< ;    0: TWdCondition(count=3094, target=)
---
> ;    0: TWdCondition(count=3063, target=)
1198c1198
< ;    0: TWdLink(count=2826, event=, unk3=)
---
> ;    0: TWdLink(count=2795, event=, unk3=)
1216c1216
< <STYLE ID="1"><TXSPN>「よぉーし、今日もいくぞぉっ！」</STYLE><PG>
---
> <STYLE ID="1"><TXSPN>「EveryOne!」</STYLE><PG>
1220c1220
< <STYLE ID="1"><TXSPN>「オオッス！！」</STYLE><PG>
---
> <STYLE ID="1"><TXSPN>「Yes!」</STYLE><PG>
1222c1222
< <STYLE ID="1"><TXSPN>野球部キャプテン・大森　健二の号令に、部員らが大きな声で応える。</STYLE><PG>
---
> <STYLE ID="1"><TXSPN>2222222。</STYLE><PG>
```

**Comment by jetstream1239** [comment]
Its so kind of u,Thanks a lot
I will try it again

**Comment by pmrowla** [comment]
Closing this as inactive, if you're still having issues feel free to re-open it. also, the CSV commands are probably the preferred way to translate/patch things now.
