### ISSUE TITLE
About lmlsb insert

### ISSUE THREAD

**Issue by noob-debug** [pmrowla/pylivemaker#17]
Hellow,I try to Translate Japanese into Chinese.
But it didn't work.
Is it because of  livemaker don't support Chinese Encoding(Some Chinese Encoding can work some but not)?
![TIM图片20200206043058](https://user-images.githubusercontent.com/60714619/73880807-1b652b80-489a-11ea-82f9-c347d5f71634.png)
![TIM图片20200206043216](https://user-images.githubusercontent.com/60714619/73880820-1f914900-489a-11ea-8734-b2eb96346382.png)

**Comment by noob-debug** [comment]
Oh i see,Thank you for your reply：）

**Comment by pmrowla** [comment]
Closing this since it's not really a pylm issue, and any discussion wrt potential engine fixes to make lm support other locales can go in #14
