### ISSUE TITLE
How to read .lsb file

### ISSUE THREAD

**Issue by keng1308** [pmrowla/pylivemaker#21]
* pylivemaker version:0.2.0
* Python version:3.8.2
* Operating System: win10 home edition
* LiveMaker game:

i have a question i extract game.exe and got a lot of .lsb file 
i try to read from https://pmrowla.com/blog/reverse-engineering-livemaker/ 
but i can't understand 
i install pylivemaker but i can't use imlsb command

**Comment by pmrowla** [comment]
> i install pylivemaker but i can't use imlsb command

It's `lmlsb` (lowercase L) not `imlsb`

see the docs:
https://pylivemaker.readthedocs.io/en/latest/cli.html#lmlsb
https://pylivemaker.readthedocs.io/en/latest/usage.html#patching-example
