### ISSUE TITLE
ModuleNotFoundError: No module named 'livemaker.cli' on linux

### ISSUE THREAD

**Issue by Stefan311** [pmrowla/pylivemaker#23]
* pylivemaker version:
0.2.1
* Python version:
3.6.9
* Operating System:
Linux Mint 19.1 Cinnamon
* LiveMaker game:

### Description
I tried to install pylivemaker:
(linux mint defaults to python2.7, so I must use explicit version 3)

 `
stefan@stefan-P55A-UD4:~$ sudo -H pip3 install pylivemaker
Collecting pylivemaker
  Downloading https://files.pythonhosted.org/packages/b6/9f/2e820c2b0ba72fa84c70eb4eea4458cae7eb3881568c2924d78298c78696/pylivemaker-0.2.1-py2.py3-none-any.whl (72kB)
    100% |████████████████████████████████| 81kB 3.4MB/s 
Collecting construct<2.10,>=2.9 (from pylivemaker)
  Downloading https://files.pythonhosted.org/packages/8d/ab/5c598494014c20f928706c826267fbe60133a77f9282829a80b6d3948635/construct-2.9.52.tar.gz (57kB)
    100% |████████████████████████████████| 61kB 5.4MB/s 
Collecting numpy>=1.16 (from pylivemaker)
  Downloading https://files.pythonhosted.org/packages/62/20/4d43e141b5bc426ba38274933ef8e76e85c7adea2c321ecf9ebf7421cedf/numpy-1.18.1-cp36-cp36m-manylinux1_x86_64.whl (20.1MB)
    100% |████████████████████████████████| 20.2MB 57kB/s 
Collecting lxml>=4.3 (from pylivemaker)
  Downloading https://files.pythonhosted.org/packages/dd/ba/a0e6866057fc0bbd17192925c1d63a3b85cf522965de9bc02364d08e5b84/lxml-4.5.0-cp36-cp36m-manylinux1_x86_64.whl (5.8MB)
    100% |████████████████████████████████| 5.8MB 203kB/s 
Collecting Pillow>=6.2.1 (from pylivemaker)
  Downloading https://files.pythonhosted.org/packages/19/5e/23dcc0ce3cc2abe92efd3cd61d764bee6ccdf1b667a1fb566f45dc249953/Pillow-7.0.0-cp36-cp36m-manylinux1_x86_64.whl (2.1MB)
    100% |████████████████████████████████| 2.1MB 525kB/s 
Collecting Click>=6.0 (from pylivemaker)
  Downloading https://files.pythonhosted.org/packages/dd/c0/4d8f43a9b16e289f36478422031b8a63b54b6ac3b1ba605d602f10dd54d6/click-7.1.1-py2.py3-none-any.whl (82kB)
    100% |████████████████████████████████| 92kB 4.8MB/s 
Collecting pydot>=1.4.1 (from pylivemaker)
  Downloading https://files.pythonhosted.org/packages/33/d1/b1479a770f66d962f545c2101630ce1d5592d90cb4f083d38862e93d16d2/pydot-1.4.1-py2.py3-none-any.whl
Collecting pyparsing>=2.1.4 (from pydot>=1.4.1->pylivemaker)
  Downloading https://files.pythonhosted.org/packages/5d/bc/1e58593167fade7b544bfe9502a26dc860940a79ab306e651e7f13be68c2/pyparsing-2.4.6-py2.py3-none-any.whl (67kB)
    100% |████████████████████████████████| 71kB 5.0MB/s 
Building wheels for collected packages: construct
  Running setup.py bdist_wheel for construct ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9vctntqe/construct/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp958dzptwpip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for construct
  Running setup.py clean for construct
Failed to build construct
Installing collected packages: construct, numpy, lxml, Pillow, Click, pyparsing, pydot, pylivemaker
  Found existing installation: construct 2.8.16
    Not uninstalling construct at /usr/lib/python3/dist-packages, outside environment /usr
  Running setup.py install for construct ... done
  Found existing installation: numpy 1.13.3
    Not uninstalling numpy at /usr/lib/python3/dist-packages, outside environment /usr
  Found existing installation: Pillow 5.1.0
    Not uninstalling pillow at /usr/lib/python3/dist-packages, outside environment /usr
Successfully installed Click-7.1.1 Pillow-7.0.0 construct-2.9.52 lxml-4.5.0 numpy-1.18.1 pydot-1.4.1 pylivemaker-0.2.1 pyparsing-2.4.6
`

An error message, but finally says "Successfully installed...". Strange. Anyway, lets try.

`
stefan@stefan-P55A-UD4:~$ lmar
Traceback (most recent call last):
  File "/usr/local/bin/lmar", line 7, in <module>
    from livemaker.cli import lmar
ModuleNotFoundError: No module named 'livemaker.cli'
`
Lets see what is installed:
`
stefan@stefan-P55A-UD4:~$ sudo -H pip3 uninstall pylivemaker
Uninstalling pylivemaker-0.2.1:
  /usr/local/bin/galconvert
  /usr/local/bin/lmar
  /usr/local/bin/lmgraph
  /usr/local/bin/lmlsb
  /usr/local/bin/lmpatch
  /usr/local/lib/python3.6/dist-packages/livemaker/GalImagePlugin.py
  /usr/local/lib/python3.6/dist-packages/livemaker/__init__.py
  /usr/local/lib/python3.6/dist-packages/livemaker/__pycache__/GalImagePlugin.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/livemaker/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/livemaker/__pycache__/archive.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/livemaker/__pycache__/exceptions.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/livemaker/__pycache__/scramble.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/livemaker/archive.py
  /usr/local/lib/python3.6/dist-packages/livemaker/exceptions.py
  /usr/local/lib/python3.6/dist-packages/livemaker/lsb/__init__.py
  /usr/local/lib/python3.6/dist-packages/livemaker/lsb/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/livemaker/lsb/__pycache__/command.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/livemaker/lsb/__pycache__/core.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/livemaker/lsb/__pycache__/lmscript.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/livemaker/lsb/__pycache__/novel.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/livemaker/lsb/command.py
  /usr/local/lib/python3.6/dist-packages/livemaker/lsb/core.py
  /usr/local/lib/python3.6/dist-packages/livemaker/lsb/lmscript.py
  /usr/local/lib/python3.6/dist-packages/livemaker/lsb/novel.py
  /usr/local/lib/python3.6/dist-packages/livemaker/scramble.py
  /usr/local/lib/python3.6/dist-packages/pylivemaker-0.2.1.dist-info/AUTHORS.rst
  /usr/local/lib/python3.6/dist-packages/pylivemaker-0.2.1.dist-info/COPYING
  /usr/local/lib/python3.6/dist-packages/pylivemaker-0.2.1.dist-info/INSTALLER
  /usr/local/lib/python3.6/dist-packages/pylivemaker-0.2.1.dist-info/METADATA
  /usr/local/lib/python3.6/dist-packages/pylivemaker-0.2.1.dist-info/RECORD
  /usr/local/lib/python3.6/dist-packages/pylivemaker-0.2.1.dist-info/WHEEL
  /usr/local/lib/python3.6/dist-packages/pylivemaker-0.2.1.dist-info/entry_points.txt
  /usr/local/lib/python3.6/dist-packages/pylivemaker-0.2.1.dist-info/top_level.txt
Proceed (y/n)? 
`

Seems cli submodule is missing at all. How can I install it?

Edit: horrible formatting, sorry

**Comment by pmrowla** [comment]
I messed up the pypi packaging, v0.2.2 should be available now with a fix, you can just run
```pip3 install --upgrade pylivemaker```

**Comment by Stefan311** [comment]
Wow, that was fast.
But seems updating the package on package server needs some time.
`Requirement already up-to-date: pylivemaker in /usr/local/lib/python3.6/dist-packages`

**Comment by pmrowla** [comment]
Yeah, you might need to wait for the pypi server stuff to propagate.

I'm not sure why the construct wheel is failing to build for you, if you still get construct errors after updating pylivemaker, you can try doing:
```
pip3 install wheel
pip3 install --upgrade --force-reinstall pylivemaker
```

**Comment by Stefan311** [comment]
Ah, now the new version is there:
Installing collected packages: pylivemaker
  Found existing installation: pylivemaker 0.2.1
    Uninstalling pylivemaker-0.2.1:
      Successfully uninstalled pylivemaker-0.2.1
Successfully installed pylivemaker-0.2.2

but still no cli:
Traceback (most recent call last):
  File "/usr/local/bin/lmar", line 7, in <module>
    from livemaker.cli import lmar
ModuleNotFoundError: No module named 'livemaker.cli'

**Comment by pmrowla** [comment]
Can you try doing `pip3 install --upgrade --force-reinstall pylivemaker`

**Comment by Stefan311** [comment]
Now its working, many thanks :)
