### ISSUE TITLE
[lmpatch] Patching exe or game archive fail for .gal picture.

### ISSUE THREAD

**Issue by H0R1Z0N** [pmrowla/pylivemaker#32]
Latest Git version
Python 3.8.2
Arch Linux Stable Branch
Anaheim

### Description

So, now that i was done having my photoshop editor translating the 16 picture i had him to do, i had to reinsert them. First off, i used a website to convert the png to bmp. The bmp2gale from the old LiveMaker3 toolkit was not working until i reopen each bmp in paint and simply save them (probably some header or something). Got them converted back to .gal. Tried to lmpatch patch them in the exe, it say to use the archive instead, did that and it failed.

### What I Did

[Screenshot of the crash dump traceback.](https://media.discordapp.net/attachments/692957886975836235/702422626756329542/unknown.png)

Take your time, i am in no hurry, meanwhile, i can finally relax and not be a freaking workholic like i was when i started. Thank for the great tool.

**Comment by H0R1Z0N** [comment]
It's due probably to me trying to patch them from a subfolder. The file are expected to be in subfolder and not root like the translation, it kinda work but lmpatch don't understand linux slash instead of backslash.

**Comment by pmrowla** [comment]
@H0R1Z0N can you try the patch from PR #35

**Comment by H0R1Z0N** [comment]
https://media.discordapp.net/attachments/692957886975836235/706337703305674802/unknown.png
I am unsure if i did apply the commit. But i did a clean install of the tool and it still happen.

**Comment by pmrowla** [comment]
`pip install git+https://github.com/pmrowla/pylivemaker.git@refs/pull/32/head` will install from the branch (you may need some combination of `install -e ...` `install --upgrade ...` etc depending on how you are installing pylivemaker)

**Comment by H0R1Z0N** [comment]
It's working, nice.

**Comment by pmrowla** [comment]
> Is it possible to reinsert a .gal image (edited and reinserted as .gal) into the game archive? lmpatch only seem to work with .lpb/.lsb files.

@Shakefrant lmpatch should work with a .gal image as long as you did not change the filename for the image. lmpatch doesn't actually care about the file type, it only checks to see that the file you are trying to replace exists in the original game archive. (`patched_lsb` is just a placeholder name for the docs/help text, it doesn't strictly have to be an LSB file)

**Comment by Shakefrant** [comment]
Thanks. 
However, how do I patch a .gal file into the right folder in the data structure? 

Main
contains game.exe and the main .lsb files
\_グラフィック   <- example of subfolder where the .gal files are that I want to replace

**Comment by pmrowla** [comment]
lmpatch assumes that wherever you are running it matches the directory structure in the original archive. If you want to patch multiple gal images, the easiest way to do it would be to make a new folder with the structure that matches the archive structure, and then place your edited images in the appropriate place in that new folder. From there you can just use the recursive option in lmpatch, which will patch everything in the target folder as long as it exists in the original archive

So if you created a folder `patch` with this content:
```
patch
└── _グラフィック
    ├── image1.gal
    └── subdir
        ├── image2.gal
        └── image3.gal
```

and then you run
```
lmpatch -r original_game.exe patch
```

It would replace `_グラフィック/image1.gal`, `_グラフィック/subdir/image2.gal`, `_グラフィック/subdir/image3.gal` in the game archive

**Comment by Shakefrant** [comment]
Thank you very much for your help.
