### ISSUE TITLE
lmlsb insert failed

### ISSUE THREAD

**Issue by jetstream1239** [pmrowla/pylivemaker#34]
hi ,i use lmlsb insert, but sometimes it failed .the log is :
no subconstruct matched: TextIns <livemaker.lsb.novel.TpWord object at 0x07EF9700> "メ ッセージボックス" 1 0 0

how can i fixed that? i guess maybe it is  a Character problem.

**Comment by pmrowla** [comment]
Your translated text most likely has characters in it which cannot be converted to shift-jis (CP932).

I just pushed a release that has a bit more accurate error message for this case, if you update to the latest pylivemaker ver (0.3.1) it should tell you what the invalid character is when you try to run `lmlsb insert`

**Comment by pmrowla** [comment]
closing this for now.

@jetstream1239 if you still have problems after upgrading to latest version, re-open the issue and include some more details (copy/pasting the command you run and the full error/traceback would be helpful)
