### ISSUE TITLE
Short question about LSB code

### ISSUE THREAD

**Issue by Stefan311** [pmrowla/pylivemaker#67]
I have seen this construction:
```
  58: Jump 0000001F.lsb:78 ((PC_行動 == 1 & PC_V == 1) & PC_移動 == 1)
  59: Jump 0000001F.lsb:71 ((PC_行動 == 2 & PC_V == 2) & PC_移動 == 1)
  60: Jump 0000001F.lsb:85 ((PC_行動 == 3 & PC_V == 3) & PC_移動 == 1)
  61: Jump 0000001F.lsb:111 1
  62: Wait 1 0 0
  63: Label 00000022
  64: Calc PC_動作 = 0
  65: Calc PC_Y = PC_Y - 1
  66: Calc PC_深度 = PC_Y + 1
  67: Jump 0000001F.lsb:775 1
  68: Wait 1 0 0
  69: Label 00000023
  70: If PC_Y % 2 == 0
  71:     Calc PC_動作 = 1
  72: Else
  73:     Calc PC_動作 = 2
```
Does the Jump from line 59 really jump into the inside of the IF-Clause at line 71? This looks really weird. Could this be a fault in disassembling?
[0000001F.lsb.zip](https://github.com/pmrowla/pylivemaker/files/4708051/0000001F.lsb.zip)

**Comment by Stefan311** [comment]
My current project: a game reverse engineering tool. Like lmlsb dump, but in html format with added links for easy navigation.
One of the early results: [0000001F.lsb.html.zip](https://github.com/pmrowla/pylivemaker/files/4708160/0000001F.lsb.html.zip)

**Comment by pmrowla** [comment]
Hmm, usually jumps should only be able to go to Label commands, but I can’t really tell if that’s a bug or not. You’d have to look at the actual LSB binary data for that jump command and see

**Comment by pmrowla** [comment]
`lmlsb validate` passes for that file, so it doesn't look like a pylm bug to me. (`validate` tests to make sure that the pylm recompiled version of the file is an exact binary match of the original)

**Comment by pmrowla** [comment]
Closing this, if it turns out to be a pylm issue feel free to reopen it
