### ISSUE TITLE
Could not read LiveMaker archive

### ISSUE THREAD

**Issue by MichaelVerdegaal** [pmrowla/pylivemaker#68]
* pylivemaker version: 0.3.2
* Python version: 3.8.1
* Operating System: Windows 10
* LiveMaker game: [VNDB](https://vndb.org/v22214)

### Description

I've been wanting to try out a small bit of hobby translating for this visual novel, and stumbled upon your repository which seems very promising. I read through the usage example but i'm pretty much stuck at the first step. 

### What I Did
I tried both the extract and the list command (results of the latter down below). I tried it on both the exe and the dat files since the readme mentioned those were supported.

Attempting to read the .exe
`lmar l 4H23.exe`
Results in this
`Could not read LiveMaker archive 4H23.exe: EXE does not contain a LiveMaker archive.`

And attempting to read the .dat file
`lmar l game.dat`
Results in this
`Could not read LiveMaker archive game.dat: Failed to parse VF directory: Error in path (parsing) -> signature
parsing expected b'vf' but parsed b'u\x00'`

### Further thoughts
This seems to suggest that it's not a LiveMaker game as it's throwing a `BadLiveMakerArchive` exception, but i know it's not the case here since the game directory contains a live.dll file. I looked around and this seems to be a thing for LiveMaker games. 
Furthermore, in the readme file of the game, the developer even explicitly states it was made in LiveMaker. 
> 本作品はlivemakerを使用して制作されました

I would like some help with figuring out why this game is failing, and how to circumvent it.

**Comment by pmrowla** [comment]
Does your game folder have a file that ends in `.ext` (like `game.ext`)? If so you need to use that file w/lmar, not `game.dat`.

Otherwise I can't really tell what the problem is without looking at the actual game, but it could be a bug in pylivemaker. If you can host it on mega or something and email me the link at peter@pmrowla.com I can take a look.

**Comment by MichaelVerdegaal** [comment]
It did indeed have a `game.ext` file. I guess this also explains why the demo needed to be extracted differently. It works now, thank you!
