### ISSUE TITLE
How do you find the TextIns Command Line Number?

### ISSUE THREAD

**Issue by DarkPulse** [pmrowla/pylivemaker#7]
As it turns out, when looking for something to decompile a LiveMaker game, google turned up your blog post - and in turn, this repository.

I've got the game's scripts decompiled fine, and thus ready to translate. I'm just confused by the process, as you say that once it's time to patch them back in, the syntax requires...

> (where 1234 is the appropriate TextIns command line number)

...and that's where I'm stumped.

Where can I find this number in a decompiled LNS? Is it the line within the LNS that begins with \<TXSPN\>? I'm not sure what to look for to find this line number; the documentation didn't explain that at all.

**Comment by pmrowla** [comment]
The `TextIns` command line number corresponds to a command line in the original LSB file, and not anything from the LNS script, so you have to be looking at a text or XML dump of the LSB. Each extracted `.lns` script file comes from a single `TextIns` command in an LSB, and they are named accordingly by pylivemaker.

For two of the LSB files from AGLS I get some scripts that look like:

```
AGLS   ❯ ll scripts-orig
-rw-r--r-- 1 pmrowla staff  472 Mar 28 20:39 00000001-00000003.lns
-rw-r--r-- 1 pmrowla staff 3.4K Mar 28 20:39 00000001-0000076D.lns
-rw-r--r-- 1 pmrowla staff 3.3K Mar 28 20:39 00000001-line87.lns
-rw-r--r-- 1 pmrowla staff 3.3K Mar 29 21:55 00000623-00000642.lns
```

The files are named as either `<LSB file>-<Label ID>.lns` or `<LSB file>-line<TextIns line #>.lns`. In general, LiveMaker outputs text scripts with the command sequence:

```
Label <some script/label ID>
Calc <some optional calculation>
TextIns <TextIns command containing the actual LNS script>
```

So for the LNS files named in the first method, you need to do a text search for the corresponding `Label` ID, and then use the line number for the subsequent `TextIns` command. For whatever reason, there are some edge cases where livemaker doesn't output a label for some scripts, and in those cases they are named with the actual `TextIns` line number by pylivemaker.

So `00000001-00000003.lns` corresponds to some label named `00000003` in the original LSB file. Looking at the text dump of the `00000001.lsb`:

```
   0: Jump 00000001.lsb:3 1
   1: Label 変数削除
   2: Exit 1
   3: Label 00000002
   4: Jump 00000001.lsb:6 1
   5: Wait 1 0 0
   6: Label 00000003
   7: Calc __メッセージ終了 = 0
   8: TextIns <livemaker.lsb.novel.TpWord object at 0x1103599e8> "メッセージボックス" 0 0 0
;pylm
; Font styles:
;---------------------------------------
; BEGIN DECOMPILED SCRIPT
;---------------------------------------
<SCENARIO VER="102">
<CONDITION ID="None">
...
```

In this case Label `00000003`  is at line number 6, and the corresponding TextIns command is at line 8, so you would use `8` as the line number for the script replacement tool. (You'll know you found the right `TextIns` command if the dumped text script here also matches the one you are trying to translate/replace).

For the other method of naming scripts (`00000001-line87.lns`) the `TextIns` command line you want would be 87, but we can double check it in the original LSB file dump as well:

```
...
  84: Call ノベルシステム\メッセージボックス\終了待ち.lsb:0  1 
  85: Call メッセージボックス作成.lsb:0  1 "ノベルタイプ"
  86: Calc __メッセージ終了 = 0
  87: TextIns <livemaker.lsb.novel.TpWord object at 0x1103c2b70> "メッセージボックス" 1 0 0
;pylm
; Font styles:
;    0: TDecorate(unk1=604, unk2=4294967295, unk3=4294967295, unk4=0, unk5=0, unk6=0, unk7=4294967295, unk8=, unk9=, unk10=4294967295, unk11=4294967295)
;---------------------------------------
; BEGIN DECOMPILED SCRIPT
;---------------------------------------
<SCENARIO VER="102">
<CONDITION ID="None">
...
```

Here you can see that there is no named `Label` before the `TextIns` command, so pylivemaker just names the .lns file with the `TextIns` line number.

Also, note that by `TextIns` command line number, pylivemaker means the actual command line number 87 and not "line number 87 in the dumped .txt file". So you find the line that starts with with `87: TextIns ...` and not just jump to the 87th line in your text editor.

**Comment by DarkPulse** [comment]
Ahh, I see! I get it now.

Admittedly I was a bit confused, too, because my experiments last night with dumping the 0000001.lsb were failing partially due to me needing to use CMD on windows to make this work - and of course, I wasn't running it via a Japanese locale, so it would crash whenever it encountered Japanese text and only dump everything that could go as regular Latin text. (Thankfully going to cmd.exe and right clicking it did allow me to do that, letting me dump the full TXT and thus giving me those labels.)

I'm not sure if something can be done about this - it's definitely trickier to do this stuff in a non-JP locale - but it's technically doable without having to resort to it, and it's also not technically a problem with the program itself, merely the vagaries of Windows character encodings.
