### ISSUE TITLE
Please teach me how to change paraphrases.

### ISSUE THREAD

**Issue by zhumating** [pmrowla/pylivemaker#71]
* pylivemaker version: 1.0.0
* Python version: 3.8.1
* Operating System: windows 10
* LiveMaker game: 

### Description
I am translating a game made by livemaker2 and there are some paraphrases like this:
![QQ图片20201015215645](https://user-images.githubusercontent.com/42637012/96139538-8b4fa980-0f31-11eb-9457-3aa64c8270f7.png)

I tried to change the small word “おとなげ" in .lns file into English and batchinsert .lns file back to .lsb file, but I failed.
There's no warning or exception, but after I extracted the new.lsb file, I found there's nothing change.
![QQ图片20201015221453](https://user-images.githubusercontent.com/42637012/96141785-f00c0380-0f33-11eb-9fad-d906adc0c317.png)

Is there any way to change these paraphrases?
Sorry for my terrible English.

### What I Did

```
>lmlsb batchinsert 00000001.lsb 00000001
Backing up original LSB.
Scenario 000003BC at line 8 will be replaced.
Scenario 000003BD at line 14 will be replaced.
Scenario 000003F5 at line 20 will be replaced.
Scenario 000003F6 at line 26 will be replaced.
Scenario 000003F7 at line 32 will be replaced.
Scenario 000003F8 at line 38 will be replaced.
Scenario 000003F9 at line 44 will be replaced.
Scenario 000003FB at line 85 will be replaced.
Scenario 000003FC at line 91 will be replaced.
Scenario 000003FF at line 136 will be replaced.
Scenario 00000400 at line 142 will be replaced.
Scenario 00000402 at line 183 will be replaced.
Scenario 00000403 at line 189 will be replaced.
Scenario 00000404 at line 195 will be replaced.
Scenario 00000405 at line 201 will be replaced.
Scenario 00000406 at line 207 will be replaced.
Scenario 00000407 at line 213 will be replaced.
Scenario 00000409 at line 254 will be replaced.
Scenario 0000040B at line 295 will be replaced.
Scenario  at line 299 will be replaced.
Scenario 0000040C at line 305 will be replaced.
Scenario 0000044C at line 346 will be replaced.
Scenario 0000044D at line 352 will be replaced.
Scenario 0000044E at line 358 will be replaced.
Scenario  at line 362 will be replaced.
Scenario 00000450 at line 374 will be replaced.
Scenario 00000451 at line 380 will be replaced.
Scenario 00000455 at line 491 will be replaced.
Scenario 00000456 at line 497 will be replaced.
Scenario 00000457 at line 503 will be replaced.
Scenario  at line 507 will be replaced.
Scenario 00000458 at line 513 will be replaced.
Scenario 0000045A at line 558 will be replaced.
Scenario 0000045B at line 564 will be replaced.
Scenario 0000045C at line 570 will be replaced.
Scenario 0000047E at line 579 will be replaced.
Scenario 0000047F at line 585 will be replaced.
Scenario 00000480 at line 591 will be replaced.
Scenario 00000481 at line 597 will be replaced.
Scenario 00000482 at line 603 will be replaced.
Scenario 00000484 at line 609 will be replaced.
Scenario 0000048D at line 638 will be replaced.
Scenario 0000048E at line 644 will be replaced.
Scenario 000004B0 at line 651 will be replaced.
Scenario 000004C1 at line 658 will be replaced.
Scenario 000004C2 at line 664 will be replaced.
Scenario 000004C7 at line 670 will be replaced.
start new_lsb_data
Wrote new LSB.
```

**Comment by pmrowla** [comment]
ruby/furigana isn't supported (or at least cannot be easily replaced) right now because I had not encountered any games that use it.

If you can upload a zip file with one or 2 of your original LSB files that contain these kinds of scripts, I can look into adding support for them.

**Comment by zhumating** [comment]
Like this……?(The zip file I upload is the game's file. Or should I make a new game and upload its file?
[00000001.zip](https://github.com/pmrowla/pylivemaker/files/5385962/00000001.zip)

**Comment by pmrowla** [comment]
That is fine. I will look into this when I get a chance.

Just to clarify, what exactly do you want to do with the furigana/ruby text? Do you want to replace the it with english text? Or do you want to remove it?

**Comment by zhumating** [comment]
Thank you very much!
I want to replace them with English text.

**Comment by pmrowla** [comment]
Do you want to only replace the ones that already exist? (this should be ok)

Or do you want to add english text placeholder text everywhere? (this may not be feasible to do in pylivemaker)

**Comment by zhumating** [comment]
the former,only replace the ones that already exist.I don't need to add text at other place.

**Comment by pmrowla** [comment]
I added some experimental support for ruby text in v1.0.1.

Using the LNS script `lmlsb extract` / `lmlsb insert` or `lmlsb batchinsert` method, `STYLE` tags in `.lns` script files now include the ruby text (when it exists).

```
<STYLE ID="1">　</STYLE><STYLE ID="11" RUBY="おとなげ">大人気</STYLE><STYLE ID="1">ない……）</STYLE><PG>
```

You can now edit the `RUBY="..."` field to contain english text like: 
```
<STYLE ID="1">　</STYLE><STYLE ID="11" RUBY="atonage">大人気</STYLE><STYLE ID="1">ない……）</STYLE><PG>
```
and then insert the translated script back into the LSB.

Note that the top of the `.lns` file will still have the 
```
;   11: TDecorate(count=3, unk2=4294967295, unk3=4294967295, unk4=0, unk5=0, unk6=0, unk7=4294967295, unk8=, ruby=おとなげ, unk10=4294967295, unk11=4294967295)
```
comment lines, but you do not need to edit anything there (those lines are ignored on script insertion and only really exist for pylm debugging purposes).

Since style tags are not supported in the CSV text block translation commands, this can only be done manually using the `.lns` files for now.

I am not sure what will actually happen when you try to run the game with the re-inserted text, since I don't have the full game to test with. I'd appreciate it if you can try this out and let me know how it works with your game.

**Comment by zhumating** [comment]
![QQ截图20201025192748](https://user-images.githubusercontent.com/42637012/97105742-4fb69b80-16f8-11eb-9d5f-3ef3e3b45eba.png)

It works!Thank you very much!Thank you very much!
