### ISSUE TITLE
Can the item or equipment be translate?

### ISSUE THREAD

**Issue by WeldingKnight** [pmrowla/pylivemaker#72]
* pylivemaker version:1.0.0
* Python version:3.8.1
* Operating System:Windows 10
* LiveMaker game:Princess Sarcrifice

### Description

i can find items name, description in 0000131A.lsb file.

```
347: Calc アイテムID = 180
 348: Calc ____d_1 = "裁ち切りハサミ【貴重品】"
 349: Calc ____d_1 = "　着衣耐久度を減らせる"
 350: Calc ____d_0 = 800
 351: Calc ____d_0 = 1
 353: Calc アイテムID = 181
 354: Calc ____d_1 = "魔法のハサミ【貴重品】"
 355: Calc ____d_1 = "　着衣耐久度を自由に設定できる"
 356: Calc ____d_0 = 0
 357: Calc ____d_0 = 1
```

but i cant edit this part.

what can i do for edit this files?

### What I Did

```
> lmlsb edit .\0000131a.lsb 348
348: Calc ____d_1 = "裁ち切りハサミ【貴重品】"

Editing Calc expression
  ____d_1 = "裁ち切りハサミ【貴重品】"
Skipping uneditable parser entry: アイテム設定文字列[0][アイテムID]
Backing up original LSB.
Wrote new LSB.
```

**Comment by pmrowla** [comment]
Can you upload a zip file with 0000131a.lsb to github? I can add support for this in `lmlsb edit`

**Comment by WeldingKnight** [comment]
[0000131A.zip](https://github.com/pmrowla/pylivemaker/files/5397461/0000131A.zip)
here it is. thank you for the quick response.

**Comment by Stefan311** [comment]
Seems this is a use-case for the extractstrings and insertstrings scripts from my [pylivemaker-tools](https://github.com/Stefan311/pylivemaker-tools)
[0000131A_translated_348.lsb.zip](https://github.com/pmrowla/pylivemaker/files/5397650/0000131A_translated_348.lsb.zip)

**Comment by pmrowla** [comment]
Marking this as closed since pylivemaker-tools should handle this case, if you run into other issues feel free to re-open this as needed
