### ISSUE TITLE
Any document about translating game system menu and in-game choice menu?

### ISSUE THREAD

**Issue by shy2052** [pmrowla/pylivemaker#73]
* pylivemaker version: 1.0.0
* Python version: 3.7.8
* Operating System: windows 7 
* LiveMaker game: Ikisugi M Lesson

### Description

Trying to translate menus such as "Save, Load, Option", and in-game choice menu.

### What I Did

Looked into https://github.com/pmrowla/pylivemaker/issues/9#issuecomment-506694249 but it is pretty hard to understand.

**Comment by pmrowla** [comment]
For translating in-game choice menus `lmlsb extractmenu` and `lmlsb insertmenu` can be used, they work the same way as `extractcsv`/`insertcsv`. I just noticed that for some reason the menu commands are missing from the docs, so I'll update that when I get a chance.

For the main system menus you have to use `lmlsb edit` to manually edit the system menu LSB files like (`ノベルシステム/システムメニュー/オプション選択時.lsb`) in See: https://github.com/pmrowla/pylivemaker/issues/19.

I think the extract/insert tool from https://github.com/Stefan311/pylivemaker-tools should also work for translating the main system menu LSB files, but I haven't tried doing it that way myself.

**Comment by shy2052** [comment]
From which file should I `extractmenu`? It seems files like 0000000A.lsb don't have menu data.

**Comment by pmrowla** [comment]
You will have to examine the LSB file contents (probably using `lmlsb dump`) to find the files containing your in-game choice menus. IIRC they should usually appear within the same LSB file containing the text script that leads into that choice menu, but it does depend on the specific game sometimes.

**Comment by shy2052** [comment]
Thank you, I'll search the files for the menu text then.
