### ISSUE TITLE
Question about Livemaker-Engine V2

### ISSUE THREAD

**Issue by xenei** [pmrowla/pylivemaker#84]
* pylivemaker version: 1.0.2
* Python version: 3.9
* Operating System: WIndows
* LiveMaker game: Version 2

Live-maker engine v2 problem with full-width characters ―

I was trying to translate a Live-maker engine game, But I found out it's using version 2 not version 3.
So Now I am having issue with the in-game characters showing up as these - 
![image](https://user-images.githubusercontent.com/91423244/140268980-5d4b8486-6b2c-45e5-a1ed-5c22b3848cdc.png)

Is there any possible way to fix this ? I've heard it is impossible but I want to be sure soo im kinda sorry for opening a issue about something a bit Off-topic.

**Comment by pmrowla** [comment]
Assuming you're talking about the full-width character spacing right? I'm only aware of being able to fix it in LM3 as described here: https://pylivemaker.readthedocs.io/en/latest/usage.html#notes-for-translation-patches

For older engine versions AFAIK there might not be anything you can do about it.

**Comment by xenei** [comment]
I see... LiveMaker-engine 2 is no hope, thanks for the reply.
