### ISSUE TITLE
Help please, command never work by saying it is not recognized operable program/batch

### ISSUE THREAD

**Issue by Billarin** [pmrowla/pylivemaker#95]
* pylivemaker version: 1.0.4
* Python version: 3.10
* Operating System: Windows
* LiveMaker game: 妄想惑星 マラトピア-益荒男と魔法の島

### Description

I was trying to extract a livemaker game and I installed livemaker already through pip.

### What I Did

```
I run lmar x game.exe -o files and this is the error I received.

'lmar' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by pmrowla** [comment]
You most likely need to add Python to your system path (make sure you have also added the `Scripts` directory as well).  See the python docs: https://docs.python.org/3.10/using/windows.html#finding-the-python-executable

Dependending on where you have Python installed, your PATH needs to include something like
```
C:\Python\Python310;C:\Python\Python310\Scripts
```

If you just check the "Add Python to PATH" box via the windows python installer it should automatically do this for you

**Comment by Billarin** [comment]
> You most likely need to add Python to your system path (make sure you have also added the `Scripts` directory as well). See the python docs: https://docs.python.org/3.10/using/windows.html#finding-the-python-executable
> 
> Dependending on where you have Python installed, your PATH needs to include something like
> 
> ```
> C:\Python\Python310;C:\Python\Python310\Scripts
> ```
> 
> If you just check the "Add Python to PATH" box via the windows python installer it should automatically do this for you
Hello, both are already in path:
http://prntscr.com/49n8HKiNXB4y
that is why i am confused.

**Comment by Billarin** [comment]
Are there any other solutions?

**Comment by pmrowla** [comment]
What files are in the folder `C:\Users\ASUS\AppData\Local\Programs\Python\Python310\Scripts`
